StockManagementMVC/ViewModels/ShipmentViewModel.cs
using StockManagementLibraries.Models;

namespace StockManagementMVC.ViewModels
{
    public class ShipmentViewModel
    {
        public IEnumerable<GPU> GPUs { get; set; }
        public IEnumerable<Laptop> Laptops { get; set; }

        public ShipmentViewModel(IEnumerable<GPU> gpus, IEnumerable<Laptop> laptops)
        {
            GPUs = gpus;
            Laptops = laptops;
        }




    }
}

StockManagementMVC/Controllers/ShipmentController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using StockManagementLibraries.Models;
using StockManagementMVC.ViewModels;

namespace StockManagementMVC.Controllers
{
    public class ShipmentController : Controller
    {

        public readonly IStockRepository<Laptop> _laptopRepository;
        public readonly IStockRepository<GPU> _gpuRepository;

        private readonly ILogger _log;


        public ShipmentController(IStockRepository<Laptop> laptopRepository, IStockRepository<GPU> gpuRepository, ILogger<LaptopController> log)
        {
            _laptopRepository = laptopRepository;
            _gpuRepository = gpuRepository;
            _log = log;
        }


        public IActionResult Index(IFormFile file)
        {
            return View(file);
        }

        public async Task<IActionResult> ShipmentDetails(IFormFile file)
        {
            IEnumerable<Laptop> _laptops = new List<Laptop>();
            IEnumerable<GPU> _gpus = new List<GPU>();
            ShipmentViewModel model = new ShipmentViewModel(_gpus, _laptops);

            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError("file", "Please select a file");
                return BadRequest(ModelState);
            }

            var fileStream = new StreamReader(file.OpenReadStream());

            var fileContent = fileStream.ReadToEndAsync().Result;
            JArray jsonArray = JArray.Parse(fileContent);
            foreach(var x in jsonArray)
            {
                var laptopSection = x["Laptop"];
                model.Laptops = JsonConvert.DeserializeObject<IEnumerable<Laptop>>(laptopSection.ToString());

                var gpuSection = x["GPU"];
                model.GPUs = JsonConvert.DeserializeObject<IEnumerable<GPU>>(gpuSection.ToString());

            }

            foreach(var item in model.Laptops)
            {
                var check = _laptopRepository.GetAll().Where(x => x.Name.ToLower().Replace(" ","") == item.Name.ToLower().Replace(" ", "")).FirstOrDefault();
                if (check == null)
                {
                    _laptopRepository.Add(item);
                }
                else
                {
                    check.Quantity += item.Quantity;
                    item.Id = check.Id;
                }
            }
            foreach (var item in model.GPUs)
            {
                var check = _gpuRepository.GetAll().Where(x => x.Name.ToLower().Replace(" ", "") == item.Name.ToLower().Replace(" ", "")).FirstOrDefault();
                if (check == null)
                {
                    _gpuRepository.Add(item);
                }
                else
                {
                    check.Quantity += item.Quantity;
                    item.Id = check.Id;
                }

            }



            return View(model);

        }

    }
}

StockManagementMVC/Views/Shipment/Index.cshtml
@model ShipmentViewModel

<form asp-action="UploadFile" enctype="multipart/form-data" >
    <div class="form-group">
        <label for="file"></label>
        <input type="file" id="file" name="File" accept="text/json" class="form-control" />
    </div>
    <input type="submit" class="btn btn-secondary" value="Submit" asp-controller="Shipment" asp-action="ShipmentDetails" />

</form>

StockManagementMVC/Views/Shipment/ShipmentDetails.cshtml
@model ShipmentViewModel



<div class="row row-cols-1 row-cols-md-3 g-4">

    @foreach (var laptop in Model.Laptops)
    {
        <div class="col">
            <div class="card laptop-card">
                <img style="max-width: 320px; max-height: 200px" src="@laptop.ImageThumbnail" class="card-img-top" alt="@laptop.Name">
                <div class="card-body laptop-button">
                    <h4 class="d-grid">
                    </h4>

                    <div class="d-flex justify-content-between mt-2">
                        <h2 class="text-start">
                            <a class="laptop-link" asp-controller="Laptop" asp-action="Details" asp-route-id="@laptop.Id">@laptop.Name</a>
                        </h2>
                        <h5 class="text-nowrap">
                            @laptop.Price.ToString("c")
                        </h5>
                    </div>

                </div>
            </div>
        </div>
    }

    @foreach (var gpu in Model.GPUs)
    {
        <div class="col">
            <div class="card gpu-card">
                <img style="max-width: 320px; max-height: 200px" src="@gpu.ImageThumbnail" class="card-img-top" alt="@gpu.Name">
                <div class="card-body gpu-button">
                    <h4 class="d-grid">
                    </h4>

                    <div class="d-flex justify-content-between mt-2">
                        <h2 class="text-start">
                            <a class="gpu-link" asp-controller="GPU" asp-action="Details" asp-route-id="@gpu.Id">@gpu.Name</a>
                        </h2>
                        <h5 class="text-nowrap">
                            @gpu.Price.ToString("c")
                        </h5>
                    </div>

                </div>
            </div>
        </div>
    }



</div>