StockManagementMVC/ViewModels/HomeViewModel.cs
using StockManagementLibraries.Models;

namespace StockManagementMVC.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Laptop> Laptops { get; set; }
        public IEnumerable<GPU> GPUs { get; set; }
        public int StockTotal { get; set; }
        public decimal PriceTotal { get; set; }

        public HomeViewModel(IEnumerable<Laptop> laptops, IEnumerable<GPU> gPUs, int stockTotal, decimal priceTotal)
        {
            Laptops = laptops;
            GPUs = gPUs;
            StockTotal = stockTotal;
            PriceTotal = priceTotal;
        }
    }
}

StockManagementMVC/ViewModels/SearchViewModel.cs
using StockManagementLibraries.Models;

namespace StockManagementMVC.ViewModels
{

    public class SearchViewModel
    {

        public string searchBy { get; set; }
        public string searchString { get; set; }
        public IEnumerable<GPU> GPUs { get; set; }
        public IEnumerable<Laptop> Laptops { get; set; }


        public SearchViewModel(string searchBy, string searchString, IEnumerable<GPU> _gpus, IEnumerable<Laptop> _laptops)
        {
            this.searchBy = searchBy;
            this.searchString = searchString;
            GPUs = _gpus;
            Laptops = _laptops;
        }
    }
}

StockManagementMVC/Controllers/GPUController.cs
using log4net;
using Microsoft.AspNetCore.Mvc;
using StockManagementLibraries.Logging;
using StockManagementLibraries.Models;
using StockManagementLibraries.Repositories;
using StockManagementMVC.ViewModels;

namespace StockManagementMVC.Controllers
{
    public class GPUController : Controller
    {
        public readonly IStockRepository<GPU> _gpuRepository;
        private readonly ILogger _log;

        public GPUController(IStockRepository<GPU> gpuRepository, ILogger<GPUController> log)
        {
            _gpuRepository = gpuRepository;
            _log = log;
        }

        public ViewResult List()
        {
            ListViewModel<GPU> gpuListViewModel = new ListViewModel<GPU>(_gpuRepository.GetAll());
            _log.LogInformation($"{LogStrings.DefaultMessage}{LogStrings.Http200}");
            return View(gpuListViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult<GPU> Create(GPU entity)
        {
            var newItem = new GPU()
            {
                Name = entity.Name,
                Brand = entity.Brand,
                Description = entity.Description,
                Quantity = entity.Quantity,
                Price = entity.Price,
                Vram = entity.Vram,
                Cuda = entity.Cuda
            };
            if(ModelState.IsValid)
            {
                _gpuRepository.Add(newItem);
                _log.LogInformation($"{LogStrings.RequestSuccessful}{LogStrings.Http201}");
                return RedirectToAction("List");
            }

            return View(newItem);
        }

        [Route("GPU/Delete/{id}")]
        public IActionResult Delete(int id)
        {
            var item = _gpuRepository.GetById(id);
            ItemViewModel<GPU> model = new ItemViewModel<GPU>(item)
            {
                Item = item
            };

            return View(model);
        }
        [Route("GPU/ConfirmDelete/{id}")]
        public IActionResult ConfirmDelete(int id)
        {
            var item = _gpuRepository.GetById(id);
            ItemViewModel<GPU> model = new ItemViewModel<GPU>(item)
            {
                Item = item
            };
            _gpuRepository.Delete(id);
            _log.LogInformation($"{LogStrings.DefaultMessage}{LogStrings.Http200}");
            return View(model);
        }

        [Route("GPU/Update/{id}")]
        public IActionResult Update(int id)
        {
            var item = _gpuRepository.GetById(id);
            var viewModel = new UpdateViewModel<GPU>();
            viewModel.Item = item;
            viewModel.UpdatedItem = new GPU();

            return View(viewModel);
        }

        [HttpPost, Route("GPU/Update/{id}")]
        public IActionResult Update(int id, UpdateViewModel<GPU> model)
        {
            var old = _gpuRepository.GetById(id);
            var updated = model.UpdatedItem;

            if (!String.IsNullOrEmpty(updated.Name))
            {
                old.Name = updated.Name;
            }
            if (!String.IsNullOrEmpty(updated.Brand))
            {
                old.Brand = updated.Brand;
            }
            if (!String.IsNullOrEmpty(updated.Description))
            {
                old.Description = updated.Description;
            }
            if (updated.Quantity != 0)
            {
                old.Quantity = updated.Quantity;
            }
            if (updated.Price != 0)
            {
                old.Price = updated.Price;
            }
            if (updated.Cuda != 0)
            {
                old.Cuda = updated.Cuda;
            }
            if (updated.Vram != 0)
            {
                old.Vram = updated.Vram;
            }
            if(updated.ImageThumbnail != null)
            {
                old.ImageThumbnail = updated.ImageThumbnail;
            }


            _gpuRepository.Update(old);
            _log.LogInformation($"{LogStrings.RequestSuccessful}{LogStrings.Http204}");
            return RedirectToAction("List");
        }

        [Route("GPU/Details/{id}")]

        public IActionResult Details(int id)
        {
            var item = _gpuRepository.GetById(id);
            if (item == null)
            {
                return NotFound();
            }
            ItemViewModel<GPU> model = new ItemViewModel<GPU>(item)
            {
                Item = item
            };

            _log.LogInformation($"{LogStrings.DefaultMessage}{LogStrings.Http200}");
            return View(model);
        }

    }
}

StockManagementMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagementLibraries.Models;
using StockManagementMVC.ViewModels;

namespace StockManagementMVC.Controllers
{
    public class HomeController : Controller
    {
        public readonly IStockRepository<GPU> _gpuRepository;
        public readonly IStockRepository<Laptop> _laptopRepository;

        public HomeController(IStockRepository<GPU> gpuRepository, IStockRepository<Laptop> laptopRepository)
        {
            _gpuRepository = gpuRepository;
            _laptopRepository = laptopRepository;
        }

        public IActionResult Index()
        {
            var laptops = _laptopRepository.GetAll();
            var gpus = _gpuRepository.GetAll();
            int totalQuantity = laptops.Sum(x => x.Quantity) + gpus.Sum(x => x.Quantity);
            var totalValue = laptops.Sum(x => x.Price * x.Quantity) + gpus.Sum(x => x.Price * x.Quantity);
            HomeViewModel model = new HomeViewModel(laptops, gpus, totalQuantity, totalValue);

            return View(model);
        }

        public IActionResult Search(string searchBy, string searchString)
        {
            List<Laptop> laptopResult = new List<Laptop>();
            List<GPU> gpuResult = new List<GPU>();
            SearchViewModel model = new SearchViewModel(searchBy, searchString, gpuResult, laptopResult);
            switch (searchBy)
            {
                case "ID":
                    laptopResult = _laptopRepository.GetAll().Where(x => x.Id.ToString() == searchString).ToList();
                    gpuResult = _gpuRepository.GetAll().Where(x => x.Id.ToString() == searchString).ToList();
                    model.Laptops = laptopResult;
                    model.GPUs = gpuResult;
                    return View(model);

                case "Name":
                    laptopResult = _laptopRepository.GetAll().Where(x => x.Name.ToLower().Contains(searchString.ToLower())).ToList();
                    gpuResult = _gpuRepository.GetAll().Where(x => x.Name.ToLower().Contains(searchString.ToLower())).ToList();
                    model.Laptops = laptopResult;
                    model.GPUs = gpuResult;
                    return View(model);

                case "Brand":
                    laptopResult = _laptopRepository.GetAll().Where(x => x.Brand.ToLower().Contains(searchString.ToLower())).ToList();
                    gpuResult = _gpuRepository.GetAll().Where(x => x.Brand.ToLower().Contains(searchString.ToLower())).ToList();
                    model.Laptops = laptopResult;
                    model.GPUs = gpuResult;
                    return View(model);

            }
            return View();
        }

    }
}

StockManagementMVC/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagementMVC.ViewModels;
using StockManagementLibraries.Models;
using log4net;
using StockManagementLibraries.Logging;
using StockManagementLibraries.Repositories;
using System.Net.WebSockets;

namespace StockManagementMVC.Controllers
{
    public class LaptopController : Controller
    {
        public readonly IStockRepository<Laptop> _laptopRepository;
        private readonly ILogger _log;


        public LaptopController(IStockRepository<Laptop> laptopRepository, ILogger<LaptopController> log)
        {
            _laptopRepository = laptopRepository;
            _log = log;
        }

        public ViewResult List()
        {
            ListViewModel<Laptop> laptopListViewModel = new ListViewModel<Laptop>(_laptopRepository.GetAll());
            _log.LogInformation($"{LogStrings.DefaultMessage}{LogStrings.Http200}");
            return View(laptopListViewModel);

        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult<Laptop> Create(Laptop entity)
        {
            var newItem = new Laptop()
            {
                Name = entity.Name,
                Brand = entity.Brand,
                Description = entity.Description,
                Quantity = entity.Quantity,
                Price = entity.Price,
                ScreenSize = entity.ScreenSize,
                Ram = entity.Ram,
                Storage = entity.Storage
            };

            if (ModelState.IsValid)
            {
                _laptopRepository.Add(newItem);
                _log.LogInformation($"{LogStrings.RequestSuccessful}{LogStrings.Http201}");
                return RedirectToAction("List");
            }

            return View(newItem);
        }

        [Route("Laptop/Delete/{id}")]
        public IActionResult Delete(int id)
        {
            var item = _laptopRepository.GetById(id);
            ItemViewModel<Laptop> model = new ItemViewModel<Laptop>(item)
            {
                Item = item
            };
            return View(model);
        }
        [Route("Laptop/ConfirmDelete/{id}")]
        public IActionResult ConfirmDelete(int id)
        {
            var item = _laptopRepository.GetById(id);
            ItemViewModel<Laptop> model = new ItemViewModel<Laptop>(item)
            {
                Item = item
            };
            _laptopRepository.Delete(id);
            _log.LogInformation($"{LogStrings.DefaultMessage}{LogStrings.Http200}");
            return View(model);
        }

        [HttpGet, Route("Laptop/Update/{id}")]
        public IActionResult Update(int id)
        {
            var item = _laptopRepository.GetById(id);
            var viewModel = new UpdateViewModel<Laptop>();
            viewModel.Item = item;
            viewModel.UpdatedItem = new Laptop();

            return View(viewModel);
        }

        [HttpPost,Route("Laptop/Update/{id}")]
        public IActionResult Update(int id,UpdateViewModel<Laptop> model)
        {

            var old = _laptopRepository.GetById(id);
            var updated = model.UpdatedItem;


            if (!string.IsNullOrEmpty(updated.Name))
            {
                old.Name = updated.Name;
            }
            if (!string.IsNullOrEmpty(updated.Brand))
            {
                old.Brand = updated.Brand;
            }
            if (!string.IsNullOrEmpty(updated.Description))
            {
                old.Description = updated.Description;
            }
            if ( updated.Quantity != 0)
            {
                old.Quantity = updated.Quantity;
            }
            if (updated.Price != 0)
            {
                old.Price = updated.Price;
            }
            if (updated.ScreenSize != 0)
            {
                old.ScreenSize = updated.ScreenSize;
            }
            if (updated.Storage != 0)
            {
                old.Storage = updated.Storage;
            }
            if (updated.Ram != 0)
            {
                old.Ram = updated.Ram;
            }
            if (updated.ImageThumbnail != null)
            {
                old.ImageThumbnail = updated.ImageThumbnail;
            }


            _laptopRepository.Update(old);
            _log.LogInformation($"{LogStrings.RequestSuccessful}{LogStrings.Http204}");
            return RedirectToAction("List");
        }

        [Route("Laptop/Details/{id}")]

        public IActionResult Details(int id)
        {
            var item = _laptopRepository.GetById(id);
            if(item == null)
            {
                return NotFound();
            }
            ItemViewModel<Laptop> model = new ItemViewModel<Laptop>(item)
            {
                Item = item
            };

            _log.LogInformation($"{LogStrings.DefaultMessage}{LogStrings.Http200}");
            return View(model);
        }

    }
}

StockManagementMVC/Views/Home/Index.cshtml
@model HomeViewModel

@{
    var gpus = Model.GPUs;
    var laptops = Model.Laptops;
    List<Stock> allStock = new List<Stock>();
    allStock.AddRange(laptops);
    allStock.AddRange(gpus);
}
<div style="height:620px; width:400px; display: block; margin-left: auto;  margin-right: auto;" 
id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://th.bing.com/th/id/R.d43915dd34b59f067a8033166681e0c4?rik=CqfNjiILxCeNAA&riu=http%3a%2f%2fclipart-library.com%2fimages%2fM8TEKopia.jpg&ehk=t02OxfLZUBS33aSvlXu%2f4Bm156y%2byxEa1vRJzNLCnjI%3d&risl=&pid=ImgRaw&r=0" class="d-block w-100" alt="...">
        </div>
        @foreach (var stock in allStock){
            <div class="carousel-item">
                <img  src="@stock.ImageThumbnail" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>@stock.Name</h5>
                </div>

            </div>
        }
        </div>

    
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Stock Type</th>
            <th scope="col">Total Stock</th>
            <th scope="col">Total Stock Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Laptop</th>
            <td>@laptops.Sum(x => x.Quantity)</td>
            <td>@laptops.Sum(x => x.Price*x.Quantity).ToString("c")</td>
        </tr>
        <tr>
            <th scope="row">GPU</th>
            <td>@gpus.Sum(x => x.Quantity)</td>
            <td>@gpus.Sum(x => x.Price*x.Quantity).ToString("c")</td>
        </tr>
        <tr>
            <th scope="row">Total</th>
            <td>@Model.StockTotal</td>
            <td>@Model.PriceTotal.ToString("c")</td>
        </tr>

    </tbody>
</table>

StockManagementMVC/Views/Home/Search.cshtml
@model SearchViewModel


<div class="row row-cols-1 row-cols-md-3 g-4">
    @{
        if(!Model.GPUs.Any() && !Model.Laptops.Any())
        {
            <h1>Search result returned null</h1>
        }
    }
    @foreach (var gpu in Model.GPUs)
    {
        <div class="col">
            <div class="card gpu-card">
                <img style="max-width: 320px; max-height: 200px" src="@gpu.ImageThumbnail" class="card-img-top" alt="@gpu.Name">
                <div class="card-body gpu-button">
                    <h3 class="d-grid">
                    </h3>

                    <div class="d-flex justify-content-between mt-2">
                        <h4 class="text-start">
                            <a class="gpu-link" asp-controller="GPU" asp-action="Details" asp-route-id="@gpu.Id">@gpu.Name</a>
                        </h4>
                        <h5 class="text-nowrap">
                            @gpu.Price.ToString("c")
                        </h5>
                    </div>

                </div>
            </div>
        </div>
    }
    @foreach (var laptop in Model.Laptops)
    {
        <div class="col">
            <div class="card laptop-card">
                <img style="max-width: 320px; max-height: 200px" src="@laptop.ImageThumbnail" class="card-img-top" alt="@laptop.Name">
                <div class="card-body laptop-button">
                    <h3 class="d-grid">
                    </h3>

                    <div class="d-flex justify-content-between mt-2">
                        <h4 class="text-start">
                            <a class="laptop-link" asp-controller="Laptop" asp-action="Details" asp-route-id="@laptop.Id">@laptop.Name</a>
                        </h4>
                        <h5 class="text-nowrap">
                            @laptop.Price.ToString("c")
                        </h5>
                    </div>

                </div>
            </div>
        </div>
    }


</div>